// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import PreviewImageController from "./preview_image_controller"
application.register("preview-image", PreviewImageController)

import ReloadController from "./reload_controller"
application.register("reload", ReloadController)
