# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: "Star Wars" }, { name: "Lord of the Rings" }])
#   Character.create(name: "Luke", movie: movies.first)
Breed.create(name: "トイプードル", kind: "dog")
Breed.create(name: "チワワ", kind: "dog")
Breed.create(name: "柴犬", kind: "dog")
Breed.create(name: "豆柴", kind: "dog")
Breed.create(name: "ミニチュアダックスフンド", kind: "dog")
Breed.create(name: "ポメラニアン", kind: "dog")
Breed.create(name: "ミニチュアシュナウザー", kind: "dog")
Breed.create(name: "ヨークシャテリア", kind: "dog")
Breed.create(name: "フレンチブルドッグ", kind: "dog")
Breed.create(name: "シーズー", kind: "dog")
Breed.create(name: "アーフェンピンシャー", kind: "dog")
Breed.create(name: "アイリッシュウォータースパニエル", kind: "dog")
Breed.create(name: "アイリッシュウルフハウンド", kind: "dog")
Breed.create(name: "アイリッシュセッター", kind: "dog")
Breed.create(name: "アイリッシュテリア", kind: "dog")
Breed.create(name: "秋田犬", kind: "dog")
Breed.create(name: "アイリッシュレッドアンドホワイトセター", kind: "dog")
Breed.create(name: "小豆柴", kind: "dog")
Breed.create(name: "アナトリアンシェパード", kind: "dog")
Breed.create(name: "アフガンハウンド", kind: "dog")
Breed.create(name: "アメリカンアキタ", kind: "dog")
Breed.create(name: "アメリカンウォータースパニエル", kind: "dog")
Breed.create(name: "アメリカンエスキモードッグ", kind: "dog")
Breed.create(name: "アメリカンコッカースパニエル", kind: "dog")
Breed.create(name: "アメリカンスタッフォードシャーテリア", kind: "dog")
Breed.create(name: "アラスカンマラミュート", kind: "dog")
Breed.create(name: "イタリアングレーハウンド", kind: "dog")
Breed.create(name: "イビザンハウンド", kind: "dog")
Breed.create(name: "イングリッシュコッカースパニエル", kind: "dog")
Breed.create(name: "イングリッシュスプリンガースパニエル", kind: "dog")
Breed.create(name: "イングリッシュセッター", kind: "dog")
Breed.create(name: "イングリッシュポインター", kind: "dog")
Breed.create(name: "イングリッシュマスティフ", kind: "dog")
Breed.create(name: "ウィペット", kind: "dog")
Breed.create(name: "ウエストハイランドホワイトテリア", kind: "dog")
Breed.create(name: "ウェルシュシープドッグ", kind: "dog")
Breed.create(name: "ウェルシュスプリンガースパニエル", kind: "dog")
Breed.create(name: "ウェルシュテリア", kind: "dog")
Breed.create(name: "エアデールテリア", kind: "dog")
Breed.create(name: "エストレラマウンテンドッグ", kind: "dog")
Breed.create(name: "オーストラリアンキャトルドッグ", kind: "dog")
Breed.create(name: "オーストラリアンケルピー", kind: "dog")
Breed.create(name: "オーストラリアンシェパード", kind: "dog")
Breed.create(name: "オーストラリアンシルキーテリア", kind: "dog")
Breed.create(name: "オーストラリアンテリア", kind: "dog")
Breed.create(name: "オールドイングリッシュシープドッグ", kind: "dog")
Breed.create(name: "甲斐犬", kind: "dog")
Breed.create(name: "カーリーコーテッドレトリバー", kind: "dog")
Breed.create(name: "カニンヘンダックスフンド", kind: "dog")
Breed.create(name: "カレリアンベアドッグ", kind: "dog")
Breed.create(name: "キースホンド", kind: "dog")
Breed.create(name: "紀州犬", kind: "dog")
Breed.create(name: "キャバチワ", kind: "dog")
Breed.create(name: "キャバプー", kind: "dog")
Breed.create(name: "キャバリア", kind: "dog")
Breed.create(name: "キングチャールズスパニエル", kind: "dog")
Breed.create(name: "クーバース", kind: "dog")
Breed.create(name: "クランバースパニエル", kind: "dog")
Breed.create(name: "グレイハウンド", kind: "dog")
Breed.create(name: "グレートデン", kind: "dog")
Breed.create(name: "グレートピレニーズ", kind: "dog")
Breed.create(name: "クロアチアンシープドッグ", kind: "dog")
Breed.create(name: "ケアンテリア", kind: "dog")
Breed.create(name: "ケリーブルーテリア", kind: "dog")
Breed.create(name: "コーイケルホンディエ", kind: "dog")
Breed.create(name: "コーギー", kind: "dog")
Breed.create(name: "ゴードンセッター", kind: "dog")
Breed.create(name: "ゴールデンドゥードル", kind: "dog")
Breed.create(name: "ゴールデンレトリバー", kind: "dog")
Breed.create(name: "コッカークス", kind: "dog")
Breed.create(name: "コッカプー", kind: "dog")
Breed.create(name: "コトン・ド・テュレアール", kind: "dog")
Breed.create(name: "コモンドール", kind: "dog")
Breed.create(name: "サーロスウルフドッグ", kind: "dog")
Breed.create(name: "サモエド", kind: "dog")
Breed.create(name: "サルーキ", kind: "dog")
Breed.create(name: "シープー", kind: "dog")
Breed.create(name: "シーポメ", kind: "dog")
Breed.create(name: "シーリハムテリア", kind: "dog")
Breed.create(name: "シェットランドシープドッグ", kind: "dog")
Breed.create(name: "シェパード", kind: "dog")
Breed.create(name: "シベリアンハスキー", kind: "dog")
Breed.create(name: "シャーペイ", kind: "dog")
Breed.create(name: "ジャーマンシェパード", kind: "dog")
Breed.create(name: "ジャーマンショートヘアードポインター", kind: "dog")
Breed.create(name: "ジャーマンスパニエル", kind: "dog")
Breed.create(name: "ジャーマンハンティングテリア", kind: "dog")
Breed.create(name: "ジャーマンピンシャー", kind: "dog")
Breed.create(name: "ジャーマンワイアーヘアードポインター", kind: "dog")
Breed.create(name: "ジャイアントシュナウザー", kind: "dog")
Breed.create(name: "ジャックラッセルテリア", kind: "dog")
Breed.create(name: "シュナウザー", kind: "dog")
Breed.create(name: "シュナプー", kind: "dog")
Breed.create(name: "シュナマル", kind: "dog")
Breed.create(name: "シーリハムテリア", kind: "dog")
Breed.create(name: "スカイテリア", kind: "dog")
Breed.create(name: "スキッパーキ", kind: "dog")
Breed.create(name: "スコティッシュテリア", kind: "dog")
Breed.create(name: "スタッフォードシャーブルテリア", kind: "dog")
Breed.create(name: "スタンダードダックスフンド", kind: "dog")
Breed.create(name: "スタンダードプードル", kind: "dog")
Breed.create(name: "スパニッシュマスティフ", kind: "dog")
Breed.create(name: "セントバーナード", kind: "dog")
Breed.create(name: "ソフトコーテッド・ウィートンテリア", kind: "dog")
Breed.create(name: "ダップー", kind: "dog")
Breed.create(name: "ダルメシアン", kind: "dog")
Breed.create(name: "チベタンスパニエル", kind: "dog")
Breed.create(name: "チベタンテリア", kind: "dog")
Breed.create(name: "チベタンマスティフ", kind: "dog")
Breed.create(name: "チャイニーズクレステッドドッグ", kind: "dog")
Breed.create(name: "チャウチャウ", kind: "dog")
Breed.create(name: "チワズー", kind: "dog")
Breed.create(name: "チワックス", kind: "dog")
Breed.create(name: "チワパグ", kind: "dog")
Breed.create(name: "チワピン", kind: "dog")
Breed.create(name: "チワプー", kind: "dog")
Breed.create(name: "チワブル", kind: "dog")
Breed.create(name: "チワマル", kind: "dog")
Breed.create(name: "狆", kind: "dog")
Breed.create(name: "トイマンチェスターテリア", kind: "dog")
Breed.create(name: "ドーベルマン", kind: "dog")
Breed.create(name: "ドゴアルヘンティーノ", kind: "dog")
Breed.create(name: "土佐犬・四国犬", kind: "dog")
Breed.create(name: "ナポリタンマスティフ", kind: "dog")
Breed.create(name: "日本スピッツ", kind: "dog")
Breed.create(name: "日本テリア", kind: "dog")
Breed.create(name: "ニューファンドランド", kind: "dog")
Breed.create(name: "ノーフォークテリア", kind: "dog")
Breed.create(name: "ノーリッチテリア", kind: "dog")
Breed.create(name: "ハバニーズ", kind: "dog")
Breed.create(name: "バーニーズマウンテンドッグ", kind: "dog")
Breed.create(name: "パグ", kind: "dog")
Breed.create(name: "パグズー", kind: "dog")
Breed.create(name: "バセットハウンド", kind: "dog")
Breed.create(name: "バセンジー", kind: "dog")
Breed.create(name: "パピキー", kind: "dog")
Breed.create(name: "パピチワ", kind: "dog")
Breed.create(name: "パピヨン", kind: "dog")
Breed.create(name: "ハリア", kind: "dog")
Breed.create(name: "パーソンラッセルテリア", kind: "dog")
Breed.create(name: "ビアデッドコリー", kind: "dog")
Breed.create(name: "ビーグル", kind: "dog")
Breed.create(name: "ビションフリーゼ", kind: "dog")
Breed.create(name: "ピットブル", kind: "dog")
Breed.create(name: "ピンプー", kind: "dog")
Breed.create(name: "ファラオハウンド", kind: "dog")
Breed.create(name: "プーリー", kind: "dog")
Breed.create(name: "プチバセットグリフォンバンデーン", kind: "dog")
Breed.create(name: "プチブラバンソン", kind: "dog")
Breed.create(name: "フラットコーテッドレトリバー", kind: "dog")
Breed.create(name: "ブラッドハウンド", kind: "dog")
Breed.create(name: "ブリタニースパニエル", kind: "dog")
Breed.create(name: "ブリュッセルグリフォン", kind: "dog")
Breed.create(name: "ブルドッグ", kind: "dog")
Breed.create(name: "ブルマスティフ", kind: "dog")
Breed.create(name: "ペキチー", kind: "dog")
Breed.create(name: "ペキックス", kind: "dog")
Breed.create(name: "ペキニーズ", kind: "dog")
Breed.create(name: "ペキプー", kind: "dog")
Breed.create(name: "ベドリントンテリア", kind: "dog")
Breed.create(name: "ベルジアングリフォン", kind: "dog")
Breed.create(name: "ベルジアングローネンダール", kind: "dog")
Breed.create(name: "ベルジアンタービュレン", kind: "dog")
Breed.create(name: "ベルジアンマリノア", kind: "dog")
Breed.create(name: "ボーダーコリー", kind: "dog")
Breed.create(name: "ボーダーテリア", kind: "dog")
Breed.create(name: "ポーチュギーズウォータードッグ", kind: "dog")
Breed.create(name: "ボクサー犬", kind: "dog")
Breed.create(name: "ボストンテリア", kind: "dog")
Breed.create(name: "北海道犬", kind: "dog")
Breed.create(name: "ポメキー", kind: "dog")
Breed.create(name: "ポメ柴", kind: "dog")
Breed.create(name: "ポメチワ", kind: "dog")
Breed.create(name: "ポメックス", kind: "dog")
Breed.create(name: "ポメパグ", kind: "dog")
Breed.create(name: "ポメプー", kind: "dog")
Breed.create(name: "ポメマル", kind: "dog")
Breed.create(name: "ポメヨン", kind: "dog")
Breed.create(name: "ポリッシュローランドシープドッグ", kind: "dog")
Breed.create(name: "ボルゾイ", kind: "dog")
Breed.create(name: "ボルドーマスティフ", kind: "dog")
Breed.create(name: "ボロニーズ", kind: "dog")
Breed.create(name: "ホワイトシェパード", kind: "dog")
Breed.create(name: "ポンスキー", kind: "dog")
Breed.create(name: "マルーキー", kind: "dog")
Breed.create(name: "マルシーズ", kind: "dog")
Breed.create(name: "マルチーズ", kind: "dog")
Breed.create(name: "マルックス", kind: "dog")
Breed.create(name: "マルパピ", kind: "dog")
Breed.create(name: "マルプー", kind: "dog")
Breed.create(name: "ミニチュアシベリアンハスキー", kind: "dog")
Breed.create(name: "ミニチュアピンシャー", kind: "dog")
Breed.create(name: "ミニチュアプードル", kind: "dog")
Breed.create(name: "ミニチュアブルテリア", kind: "dog")
Breed.create(name: "ヨーチー", kind: "dog")
Breed.create(name: "ヨープー", kind: "dog")
Breed.create(name: "ラサアプソ", kind: "dog")
Breed.create(name: "ラフコリー", kind: "dog")
Breed.create(name: "ラブラドールレトリバー", kind: "dog")
Breed.create(name: "ラブラドゥードル", kind: "dog")
Breed.create(name: "レークランドテリア", kind: "dog")
Breed.create(name: "レオンベルガー", kind: "dog")
Breed.create(name: "ロットワイラー", kind: "dog")
Breed.create(name: "ワイマラナー", kind: "dog")
Breed.create(name: "ワイヤーフォックステリア", kind: "dog")
Breed.create(name: "ミックス", kind: "dog")


Breed.create(name: "MIX", kind: "cat")
Breed.create(name: "スコティッシュ・フォールド", kind: "cat")
Breed.create(name: "マンチカン", kind: "cat")
Breed.create(name: "アメリカンショートヘアー", kind: "cat")
Breed.create(name: "ノルウェージャンフォレストキャット", kind: "cat")
Breed.create(name: "ブリティッシュショートヘアー", kind: "cat")
Breed.create(name: "ラグドール", kind: "cat")
Breed.create(name: "ロシアンブルー", kind: "cat")
Breed.create(name: "ペルシャ", kind: "cat")
Breed.create(name: "ベンガル", kind: "cat")
Breed.create(name: "アビシニアン", kind: "cat")
Breed.create(name: "アメリカンカール", kind: "cat")
Breed.create(name: "アメリカンワイヤーヘアー", kind: "cat")
Breed.create(name: "エキゾチック", kind: "cat")
Breed.create(name: "エジプシャンマウ", kind: "cat")
Breed.create(name: "オシキャット", kind: "cat")
Breed.create(name: "オリエンタルショートヘアー", kind: "cat")
Breed.create(name: "キムリック", kind: "cat")
Breed.create(name: "コーニッシュ・レックス", kind: "cat")
Breed.create(name: "コラット", kind: "cat")
Breed.create(name: "サイベリアン", kind: "cat")
Breed.create(name: "ジャパニーズ・ボブテイル", kind: "cat")
Breed.create(name: "シャム", kind: "cat")
Breed.create(name: "シャルトリュー", kind: "cat")
Breed.create(name: "シンガプーラ", kind: "cat")
Breed.create(name: "スクーカム", kind: "cat")
Breed.create(name: "スフィンクス", kind: "cat")
Breed.create(name: "セルカーク・レックス", kind: "cat")
Breed.create(name: "ソマリ", kind: "cat")
Breed.create(name: "ターキッシュ・アンゴラ", kind: "cat")
Breed.create(name: "ターキッシュ・バン", kind: "cat")
Breed.create(name: "デボンレックス", kind: "cat")
Breed.create(name: "トンキニーズ", kind: "cat")
Breed.create(name: "日本ネコ", kind: "cat")
Breed.create(name: "バーマン", kind: "cat")
Breed.create(name: "バーミーズ", kind: "cat")
Breed.create(name: "ハバナブラウン", kind: "cat")
Breed.create(name: "バリニーズ", kind: "cat")
Breed.create(name: "ヒマラヤン", kind: "cat")
Breed.create(name: "ボンベイ", kind: "cat")
Breed.create(name: "マンクス", kind: "cat")
Breed.create(name: "マンチカール", kind: "cat")
Breed.create(name: "メインクーン", kind: "cat")
Breed.create(name: "ラガマフィン", kind: "cat")
Breed.create(name: "ラパーマ", kind: "cat")


FavoriteToyDog.create(name: "ボール")
FavoriteToyDog.create(name: "ぬいぐるみ")
FavoriteToyDog.create(name: "ロープ")
FavoriteToyDog.create(name: "コング")
FavoriteToyDog.create(name: "フリスビー")
FavoriteToyDog.create(name: "デンタルトイ")


FavoriteTreatDog.create(name: "ちゅーる")
FavoriteTreatDog.create(name: "歯磨きガム")
FavoriteTreatDog.create(name: "にぼし")
FavoriteTreatDog.create(name: "おいも")
FavoriteTreatDog.create(name: "ジャーキー")
FavoriteTreatDog.create(name: "チーズ")
FavoriteTreatDog.create(name: "ささみ")
FavoriteTreatDog.create(name: "ビスケット")
FavoriteTreatDog.create(name: "ドライフルーツ")
